### ISSUE TITLE
Order in options

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/Generaptor#19]
```fsharp
        step(
             name = "Cache artifacts",
             uses = "actions/cache@v4",
             options = Map.ofList [
                "path", "artifacts"
                "key", $"{platform}.{architecture}." + "${{ hashFiles('.github/cache-key.json') }}"
            ]
        )
```

This leads to
```yml
    - name: Cache artifacts
      uses: actions/cache@v4
      with:
        key: linux.x86-64.${{ hashFiles('.github/cache-key.json') }}
        path: artifacts
```

The order of options is reversed. We should consider an order-preserving variant if possible.
