### ISSUE TITLE
Order in envs

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/Generaptor#20]
```fsharp
        let testEnv =
            [
                "DOTNET_NOLOGO", "1"
                "DOTNET_CLI_TELEMETRY_OPTOUT", "1"
                "NUGET_PACKAGES", "${{ github.workspace }}/.github/nuget-packages"
                "PACKAGE_VERSION_BASE", "1.8.21"
            ] |> Seq.map(fun (k, v) -> setEnv k v)
```

This leads to
```yml
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages
      PACKAGE_VERSION_BASE: 1.8.21
```

Order should be preserved.
